Repository Flash-Team/Flash_Backend, pull requests merged in 2020-04, with the labels that each got.

#7 Added to organization,product apps views,urls,serializers
  flash/order/migrations/0003_auto_20200407_0035.py
  flash/organization/migrations/0002_auto_20200407_0035.py
  flash/organization/serializers.py
  flash/organization/urls.py
  flash/organization/views.py
  flash/product/bases.py
  flash/product/migrations/0005_auto_20200407_0035.py
  flash/product/serializers.py
  flash/product/urls.py
  flash/product/views.py
  flash/urls.py
Labels: enhancement

#8 Fixed mistakes in organization, product apps views
  flash/organization/serializers.py
  flash/organization/urls.py
  flash/organization/views.py
  flash/product/views.py
  flash/urls.py
Labels: bug

#9 Rating order and user url
  flash/_auth/serializers.py
  flash/_auth/urls.py
  flash/_auth/views.py
  flash/order/migrations/0004_auto_20200407_1226.py
  flash/order/migrations/0005_auto_20200407_1229.py
  flash/order/models.py
  flash/order/serializers.py
  flash/order/urls.py
  flash/order/views.py
Labels: enhancement

#10 Order creation
  flash/_auth/apps.py
  flash/_auth/models.py
  flash/_auth/serializers.py
  flash/_auth/validators.py
  flash/order/__init__.py
  flash/order/apps.py
  flash/order/filters.py
  flash/order/migrations/0006_auto_20200412_0706.py
  flash/order/migrations/0007_auto_20200413_0453.py
  flash/order/models.py
  flash/order/serializers.py
  flash/order/signals.py
  flash/order/validators.py
  flash/order/views.py
  flash/settings.py
  requirements.txt
Labels: enhancement

#11 Orders Logging Permissions
  .gitignore
  flash/_auth/admin.py
  flash/_auth/migrations/0002_auto_20200414_0555.py
  flash/_auth/migrations/0003_auto_20200414_0555.py
  flash/_auth/models.py
  flash/_auth/serializers.py
  flash/_auth/urls.py
  flash/_auth/validators.py
  flash/_auth/views.py
  flash/order/filters.py
  flash/order/migrations/0008_auto_20200414_0821.py
  flash/order/models.py
  flash/order/serializers.py
  flash/order/views.py
  flash/settings.py
Labels: enhancement

#12 Signals
  flash/_auth/admin.py
  flash/_auth/migrations/0004_auto_20200416_1337.py
  flash/_auth/models.py
  flash/_auth/views.py
  flash/order/admin.py
  flash/order/filters.py
  flash/order/models.py
  flash/order/permissions.py
  flash/order/serializers.py
  flash/order/signals.py
  flash/order/validators.py
  flash/order/views.py
Labels: enhancement

#13 Tests
  flash/_auth/tests.py
  flash/_auth/views.py
  flash/order/models.py
  flash/order/tests.py
  flash/order/views.py
  flash/settings.py
  flash/urls.py
  requirements.txt
Labels: dependencies, enhancement

#16 Fixes
  .gitignore
  flash/_auth/serializers.py
  flash/order/admin.py
  flash/order/views.py
  flash/organization/permissions.py
  flash/organization/signals.py
  flash/organization/tests.py
  flash/organization/validators.py
  flash/organization/views.py
  flash/product/bases.py
  flash/product/models.py
  flash/product/serializers.py
  flash/product/signals.py
  flash/product/tests.py
  flash/product/validators.py
  flash/settings.py
  flash/wsgi.py
Labels: bug

#17 Added permissions, Manager, UserViewSet
  flash/_auth/urls.py
  flash/_auth/views.py
  flash/organization/models.py
  flash/organization/serializers.py
  flash/organization/views.py
  flash/product/models.py
  flash/product/serializers.py
  flash/product/views.py
Labels: enhancement

#18 Logging
  README.md
  flash/_auth/views.py
  flash/order/signals.py
  flash/order/views.py
  flash/organization/signals.py
  flash/organization/views.py
  flash/product/signals.py
  flash/product/views.py
  flash/settings.py
Labels: documentation, enhancement
